### ISSUE TITLE
Error logs

### ISSUE THREAD

**Issue by MystK** [MystK/delta-bot-three#225]
@wyantb found some errors in the error logs. Unknown root cause at the moment but I think it requires investigation.

````
(node:11113) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): StatusCodeError: 401 - {"message":"Unauthorized","error":401}
(node:11113) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:11113) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: Cannot read property 'children' of undefined
Failed to find delta log post NotFoundError: Key not found in database [t3_7xjv31]
    at /home/db3/delta-bot-three/node_modules/levelup/lib/levelup.js:164:15
    at /home/db3/delta-bot-three/node_modules/encoding-down/index.js:50:21
Failed to find delta log post NotFoundError: Key not found in database [t3_7x8rl7]
    at /home/db3/delta-bot-three/node_modules/levelup/lib/levelup.js:164:15
    at /home/db3/delta-bot-three/node_modules/encoding-down/index.js:50:21
Failed to find delta log post NotFoundError: Key not found in database [t3_7xipte]
    at /home/db3/delta-bot-three/node_modules/levelup/lib/levelup.js:164:15
    at /home/db3/delta-bot-three/node_modules/encoding-down/index.js:50:21
Failed to find delta log post NotFoundError: Key not found in database [t3_7xkaka]
    at /home/db3/delta-bot-three/node_modules/levelup/lib/levelup.js:164:15
    at /home/db3/delta-bot-three/node_modules/encoding-down/index.js:50:21
(node:11167) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): StatusCodeError: 401 - {"message":"Unauthorized","error":401}
(node:11167) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:11167) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: Cannot read property 'children' of undefined
Failed to find delta log post NotFoundError: Key not found in database [t3_7xe5ju]
    at /home/db3/delta-bot-three/node_modules/levelup/lib/levelup.js:164:15
    at /home/db3/delta-bot-three/node_modules/encoding-down/index.js:50:21
Failed to find delta log post NotFoundError: Key not found in database [t3_7xm22k]
    at /home/db3/delta-bot-three/node_modules/levelup/lib/levelup.js:164:15
    at /home/db3/delta-bot-three/node_modules/encoding-down/index.js:50:21
(node:11216) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): StatusCodeError: 401 - {"message":"Unauthorized","error":401}
(node:11216) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:11216) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: Cannot read property 'children' of undefined
Failed to find delta log post NotFoundError: Key not found in database [t3_7xlm7x]
    at /home/db3/delta-bot-three/node_modules/levelup/lib/levelup.js:164:15
    at /home/db3/delta-bot-three/node_modules/encoding-down/index.js:50:21
Failed to find delta log post NotFoundError: Key not found in database [t3_7xmko6]
    at /home/db3/delta-bot-three/node_modules/levelup/lib/levelup.js:164:15
    at /home/db3/delta-bot-three/node_modules/encoding-down/index.js:50:21
(node:11276) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): StatusCodeError: 401 - {"message":"Unauthorized","error":401}
(node:11276) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:11276) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): TypeError: Cannot read property 'children' of undefined
Failed to find delta log post NotFoundError: Key not found in database [t3_7xmfe0]
    at /home/db3/delta-bot-three/node_modules/levelup/lib/levelup.js:164:15
    at /home/db3/delta-bot-three/node_modules/encoding-down/index.js:50:21
````

**Comment by wyantb** [comment]
Oof, yeah, definitely warrants investigation. Is this related to the bot being down that someone posted in the Slack channel about? Do you have a full copy of the logs stored anywhere, or at least the last MB of them or something?

I've set myself a reminder, but please poke me again tomorrow/Saturday. Unfortunately no free time for it today :(

**Comment by MystK** [comment]
havn't seen this in a while so will close
